spring.application.name: tippwertung


server.port: 7082

# H2
spring.h2.console.enabled: true
spring.h2.console.path: /h2
h2.tcp.enabled: true
h2.tcp.port: 7092

# Datasource
spring.datasource:
  url: jdbc:h2:file:~/tippwertung
  username: sa
  password:

# Kafka
spring.kafka:
  bootstrap-servers: ${spring.embedded.kafka.brokers:localhost:9092}
  consumer:
    group-id: ${spring.application.name}
    auto-offset-reset: latest
    key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# Logging
logging.level.root: INFO
